import './globals.css'
import type { Metadata } from 'next'
import {Raleway, Open_Sans } from 'next/font/google'

const raleway = Raleway({ subsets: ['latin'], weight: ['400', '700'], variable: '--fonto-raleway' })
const openSans = Open_Sans({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-open-sans' })

export const metadata: Metadata = {
  title: 'Fylo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${openSans.variable} text-[hsl(0, 0%, 100%)] font-sans text-sm font-normal h-screen bg-primary-main`}>{children}</body>
    </html>
  )
}
